# Generated by scripts/homebrew/render.mjs for codegraph 0.1.0 — do not edit by hand.
cask "codegraph" do
  version "0.1.0"
  arch arm: "osx-arm64", intel: "osx-x64"
  sha256 arm:   "947783ac9155dee78dc5969570382d320af851cfda3d4adc9702210c19c25a4f",
         intel: "838af78a613b92f1a54cec59a411ea5aad8a594f685dc1a9491a03b772d76734"

  url "https://github.com/defsquare/codegraph/releases/download/v#{version}/Codegraph-#{version}-#{arch}.dmg"
  name "Codegraph"
  desc "Code city and dependency navigator over multi-language code models"
  homepage "https://github.com/defsquare/codegraph"

  livecheck do
    url :url
    strategy :github_latest
  end

  auto_updates false
  depends_on macos: ">= :monterey"

  app "Codegraph.app"
  # The single-executable codegraph (CLI + daemon) that rides in the bundle.
  binary "#{appdir}/Codegraph.app/Contents/MacOS/codegraph"

  zap trash: "~/Library/Application Support/codegraph"
end
