# Generated by scripts/homebrew/render.mjs for codegraph 0.1.0 — do not edit by hand.
class CodegraphJava < Formula
  desc "Codegraph extractor for Java (Spoon, a GraalVM native image)"
  homepage "https://github.com/defsquare/codegraph"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/defsquare/codegraph/releases/download/v0.1.0/codegraph-java-osx-arm64"
      sha256 "e78b979659de70d6373facb37b28bab529b20b41a0d2c5162d6b15bad2b68049"
    end
    on_intel do
      url "https://github.com/defsquare/codegraph/releases/download/v0.1.0/codegraph-java-osx-x64"
      sha256 "a4aed76fcb227aa18178444415f1f1d85e8487a05fdaf2ef2d2f6da75892d9e6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/defsquare/codegraph/releases/download/v0.1.0/codegraph-java-linux-arm64"
      sha256 "5388f824562353ebbbc8aaf2c5fa984af054f28a21807c6310a8cb207a7eebf1"
    end
    on_intel do
      url "https://github.com/defsquare/codegraph/releases/download/v0.1.0/codegraph-java-linux-x64"
      sha256 "1a3ea03008d7b8aeb2884573aead213487efe952d568eda71ae690394df571ca"
    end
  end

  def install
    # The download is the bare asset, named after its RID; the command is not.
    bin.install Dir["codegraph-java-*"].first => "codegraph-java"
  end

  test do
    system bin/"codegraph-java", "--version"
    (testpath/"src").mkpath
    (testpath/"src/Hello.java").write "class Hello { }"
    system bin/"codegraph-java", "--src", testpath/"src", "--out", testpath/"model.jsonl", "--progress", "none"
    assert_predicate testpath/"model.jsonl", :exist?
  end
end
