# Generated by scripts/homebrew/render.mjs for codegraph 0.1.0 — do not edit by hand.
class CodegraphElixir < Formula
  desc "Codegraph extractor for Elixir (the compiler's parser, a Burrito binary)"
  homepage "https://github.com/defsquare/codegraph"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/defsquare/codegraph/releases/download/v0.1.0/codegraph-elixir-osx-arm64"
      sha256 "1231c8e5eac9df46a8462954c6b78a9ad19f7342050389906ee89f979c141cdf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/defsquare/codegraph/releases/download/v0.1.0/codegraph-elixir-linux-x64"
      sha256 "294136b3c16b91743e7a0182c8bf6120fa2171a75dee54e99cb027af599e1213"
    end
  end

  def install
    # The download is the bare asset, named after its RID; the command is not.
    bin.install Dir["codegraph-elixir-*"].first => "codegraph-elixir"
  end

  test do
    system bin/"codegraph-elixir", "--version"
    (testpath/"src").mkpath
    (testpath/"src/hello.ex").write "defmodule Hello do\nend\n"
    system bin/"codegraph-elixir", "--src", testpath/"src", "--out", testpath/"model.jsonl", "--progress", "none"
    assert_predicate testpath/"model.jsonl", :exist?
  end
end
