# Generated by scripts/homebrew/render.mjs for codegraph 0.1.0 — do not edit by hand.
class CodegraphTypescript < Formula
  desc "Codegraph extractor for TypeScript (the compiler API, no build needed)"
  homepage "https://github.com/defsquare/codegraph"
  url "https://registry.npmjs.org/codegraph-typescript/-/codegraph-typescript-0.1.0.tgz"
  sha256 "c281d17e369094942b0d4aa7c4015546beabf9d787b303de9d7ea12a7640789c"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    system bin/"codegraph-typescript", "--version"
    (testpath/"src").mkpath
    (testpath/"src/hello.ts").write "export const hello = 1;"
    system bin/"codegraph-typescript", "--src", testpath/"src", "--out", testpath/"model.jsonl", "--progress", "none"
    assert_predicate testpath/"model.jsonl", :exist?
  end
end
