# Generated by scripts/homebrew/render.mjs for codegraph 0.1.0 — do not edit by hand.
class CodegraphCsharp < Formula
  desc "Codegraph extractor for C# (Roslyn, a .NET single-file binary)"
  homepage "https://github.com/defsquare/codegraph"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/defsquare/codegraph/releases/download/v0.1.0/codegraph-csharp-osx-arm64"
      sha256 "37ed7ef5a6367c0813410666d5ffd1e6e279aa79e4359efd67f05b2c7c2595ab"
    end
    on_intel do
      url "https://github.com/defsquare/codegraph/releases/download/v0.1.0/codegraph-csharp-osx-x64"
      sha256 "417ee6b701d640f71e05c7adaf6285cf51038d822d1811f23aaa643707ac41d5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/defsquare/codegraph/releases/download/v0.1.0/codegraph-csharp-linux-arm64"
      sha256 "19288d1e71ec02b0221a24d6cd9ccd0ee5dcfa3bb3992ecded2cab2d2415e389"
    end
    on_intel do
      url "https://github.com/defsquare/codegraph/releases/download/v0.1.0/codegraph-csharp-linux-x64"
      sha256 "47c7bec81628c1bb4b8562fc65a630bb29e297aa94de36e0fa93e90bfbbb1519"
    end
  end

  def install
    # The download is the bare asset, named after its RID; the command is not.
    bin.install Dir["codegraph-csharp-*"].first => "codegraph-csharp"
  end

  test do
    system bin/"codegraph-csharp", "--version"
    (testpath/"src").mkpath
    (testpath/"src/Hello.cs").write "class Hello { }"
    system bin/"codegraph-csharp", "--src", testpath/"src", "--out", testpath/"model.jsonl", "--progress", "none"
    assert_predicate testpath/"model.jsonl", :exist?
  end
end
